import {
    ListChecks,
    BookOpen,
    MessageSquareText,
    Handshake,
    Megaphone,
    SmilePlus,
    ScrollText,
    FolderArchive,
    FileCheck,
    Scale,
    Briefcase,
    Accessibility,
    Gavel,
    HandCoins,
    FileWarning,
    Users,
    CalendarClock,
    Globe,
    BarChart3,
    ClipboardCheck,
    Home,
    Smartphone,
    PenLine,
    Radio,
    Bot,
    PhoneCall,
    Newspaper,
    type LucideIcon,
} from "lucide-react";
import type { LocalizedString } from "@/context/LanguageContext";

export interface StaticModule {
    id: string;
    name: LocalizedString;
    icon: LucideIcon;
}

export const modulesData: StaticModule[] = [
    { id: "online-list-registration", name: { en: "Online List Registration", ne: "अनलाईन सूची दर्ता" }, icon: ListChecks },
    { id: "registration-and-dispatch", name: { en: "Registration & Dispatch", ne: "दर्ता–चलानी" }, icon: BookOpen },
    { id: "note-correspondence-management", name: { en: "Note / Correspondence Management", ne: "टिप्पणी / पत्राचार व्यवस्थापन" }, icon: MessageSquareText },
    { id: "ossd", name: { en: "One Step Service Delivery (OSSD)", ne: "One Step Service Delivery (OSSD)" }, icon: Handshake },
    { id: "hello-mayor", name: { en: "Hello Mayor (Hello Local Level)", ne: "Hello Mayor (हेलो स्थानीय तह)" }, icon: Megaphone },
    { id: "service-recipient-satisfaction-survey", name: { en: "Service Recipient Satisfaction Survey System", ne: "सेवाग्राही सन्तुष्टि सर्वेक्षण प्रणाली" }, icon: SmilePlus },
    { id: "digital-citizen-charter", name: { en: "Digital Citizen Charter", ne: "डिजिटल नागरिक बडापत्र" }, icon: ScrollText },
    { id: "digital-record-management", name: { en: "Digital Record Management", ne: "डिजिटल अभिलेख व्यवस्थापन" }, icon: FolderArchive },
    { id: "online-recommendation", name: { en: "Online Recommendation", ne: "अनलाइन सिफारिस" }, icon: FileCheck },
    { id: "legal-archive", name: { en: "Record Management (Legal Archive)", ne: "अभिलेख व्यवस्थापन (Legal Archive)" }, icon: Scale },
    { id: "business-registration-renewal", name: { en: "Business Registration / Renewal", ne: "व्यवसाय दर्ता / नवीकरण" }, icon: Briefcase },
    { id: "disability-senior-citizen", name: { en: "Disability / Senior Citizen", ne: "अपाङ्गता / ज्येष्ठ नागरिक" }, icon: Accessibility },
    { id: "judicial-committee-management", name: { en: "Judicial Committee (Ijlas) Management", ne: "इजलास (न्यायिक) व्यवस्थापन" }, icon: Gavel },
    { id: "grant-mis", name: { en: "Grant Management — Grant MIS", ne: "अनुदान व्यवस्थापन — Grant MIS" }, icon: HandCoins },
    { id: "beruju-system", name: { en: "Irregularity Management — Beruju System", ne: "बेरुजु व्यवस्थापन — Beruju System" }, icon: FileWarning },
    { id: "employee-management-pis", name: { en: "Employee Management (PIS)", ne: "कर्मचारी व्यवस्थापन (PIS)" }, icon: Users },
    { id: "appointment-system", name: { en: "Appointment System", ne: "Appointment System" }, icon: CalendarClock },
    { id: "digital-web-profile-portal", name: { en: "Digital / Web-based Profile Portal", ne: "डिजिटल/वेबबेस प्रोफाइल पोर्टल" }, icon: Globe },
    { id: "monitoring-and-evaluation-system", name: { en: "Monitoring and Evaluation System", ne: "अनुगमन र मूल्यांकन प्रणाली" }, icon: BarChart3 },
    { id: "planning-management", name: { en: "Planning Management (Lite, Pro, Advance)", ne: "योजना व्यवस्थापन (Lite, Pro, Advance)" }, icon: ClipboardCheck },
    { id: "electronic-house-map-system", name: { en: "Electronic House Map System", ne: "बिधुतिया घर नक्सा प्रणाली" }, icon: Home },
    { id: "integrated-mobile-apps", name: { en: "Integrated Mobile Apps", ne: "मोबाइल एप (Integrated Mobile apps)" }, icon: Smartphone },
    { id: "integration-digital-signature", name: { en: "Integration Digital Signature", ne: "Integration Digital Signature" }, icon: PenLine },
    { id: "airfone-ivr", name: { en: "AIRfone (Digital IVR Call System)", ne: "AIRfone (डिजिटल IVR Call System)" }, icon: Radio },
    { id: "ai-chatbot", name: { en: "AI ChatBot", ne: "AI ChatBot" }, icon: Bot },
    { id: "ai-call-system", name: { en: "AI Call System", ne: "AI Call सिस्टम" }, icon: PhoneCall },
    { id: "icms-portal", name: { en: "Integrated Content Management System (iCMS) Portal", ne: "एकिकृत कन्टेन्ट व्यवस्थापन प्रणाली (iCMS) पोर्टल" }, icon: Newspaper },
];
